language: go
before_script:
  - git clone --depth 1 https://github.com/sstephenson/bats.git
  - export PATH=$PATH:bats/bin
  - go get code.google.com/p/go.tools/cmd/cover
go:
  - 1.3
  - tip
install:
  - go get -d -t -u
matrix:
  allow_failures:
    - go: tip
